to fix exception 1 below test switched to using once created project. setUp just check if it is created and use it or create a new one.
delete project is commented out in abstract class, because it always shrows exceptions cannot delete project. 

Exception 1
--------------
	Resource '/warprj' already exists.

org.eclipse.core.internal.resources.ResourceException: Resource '/warprj' already exists.
at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:289)
at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:276)
at org.eclipse.core.internal.resources.Project.create(Project.java:225)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.create(FacetedProjectFrameworkImpl.java:717)
at org.eclipse.wst.common.project.facet.core.ProjectFacetsManager.create(ProjectFacetsManager.java:399)
at org.jboss.tools.seam.core.test.project.facet.AbstractSeamFacetTest.createSeamProject(AbstractSeamFacetTest.java:142)
at org.jboss.tools.seam.core.test.project.facet.AbstractSeamFacetTest.createSeamWarProject(AbstractSeamFacetTest.java:157)
at org.jboss.tools.seam.core.test.project.facet.Seam2FacetInstallDelegateTest.setUp(Seam2FacetInstallDelegateTest.java:62)
at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:354)
at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:206)
at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:35)
at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:31)
at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethod(EclipseAppContainer.java:572)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:171)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:106)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:76)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:363)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:508)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:447)
at org.eclipse.equinox.launcher.Main.run(Main.java:1173)
at org.eclipse.equinox.launcher.Main.main(Main.java:1148)
at org.eclipse.core.launcher.Main.main(Main.java:30)

git-svn-id: http://svn.jboss.org/repos/jbosstools/trunk@4799 a97e2381-89e5-4abb-bab3-167db6db766c